# Generated by Django 5.1.7 on 2025-03-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sitesetup_alter_menulink_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
        migrations.AddField(
            model_name='menulink',
            name='site_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.sitesetup'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_description',
            field=models.BooleanField(default=True, verbose_name='Mostrar descrição'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_footer',
            field=models.BooleanField(default=True, verbose_name='Mostrar footer'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_header',
            field=models.BooleanField(default=True, verbose_name='Mostrar header'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_menu',
            field=models.BooleanField(default=True, verbose_name='Mostrar menu'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_pagination',
            field=models.BooleanField(default=True, verbose_name='Mostrar paginação'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_search',
            field=models.BooleanField(default=True, verbose_name='Mostrar busca'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Título'),
        ),
    ]
