# Generated by Django 5.1.7 on 2025-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_sitesetup_options_menulink_site_setup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='favicon/%Y/%m/', verbose_name='Favicon'),
        ),
    ]
