# Generated by Django 5.1.7 on 2025-03-12 16:33

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='favicon/', validators=[utils.model_validators.validate_png], verbose_name='Favicon'),
        ),
    ]
