# Generated by Django 5.1.7 on 2025-03-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Precisa estar marcado para a página ser exibida.', verbose_name='Publicar'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True)),
                ('excerpt', models.CharField(max_length=255, verbose_name='Resumo')),
                ('is_published', models.BooleanField(default=False, help_text='Precisa estar marcado para a página ser exibida.', verbose_name='Publicar')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('cover', models.ImageField(blank=True, default='', upload_to='posts', verbose_name='Imagem da capa')),
                ('cover_in_post', models.BooleanField(default=True, help_text='Exibe a imagem da capa no conteúdo do post.', verbose_name='Imagem no post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, default='', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
