# Generated by Django 5.1.7 on 2025-03-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_create_by_post_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
