# Generated by Django 5.1.7 on 2025-03-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_postattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
    ]
