# Generated by Django 5.1.7 on 2025-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_sitesetup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='new_tab',
            field=models.BooleanField(default=False, verbose_name='Nova aba?'),
        ),
    ]
